import React, { useState, useEffect } from 'react';
import axios from 'axios';

const GateScanner = () => {
    const [scanResult, setScanResult] = useState('');
    const [status, setStatus] = useState(null);
    const [loading, setLoading] = useState(false);
    const [chargers, setChargers] = useState([]);

    useEffect(() => {
        // Fetch chargers to map ID to Name later
        axios.get('/api/chargers').then(res => setChargers(res.data)).catch(console.error);
    }, []);

    const handleScan = async () => {
        if (!scanResult) return;
        setLoading(true);
        setStatus(null);

        // Simulating network delay for realism/animation
        setTimeout(async () => {
            try {
                const res = await axios.post('/api/qr/verify', { qr_code: scanResult });

                // Find charger name
                const charger = chargers.find(c => c.id === res.data.charger_id);
                const chargerName = charger ? charger.name : `Charger #${res.data.charger_id}`;
                // Deterministic Slot ID matching App.jsx
                const slotId = `Slot-A${res.data.charger_id}`;

                setStatus({
                    success: true,
                    msg: 'ACCESS GRANTED',
                    details: 'Verification Successful',
                    chargerName: chargerName,
                    slotId: slotId
                });
            } catch (err) {
                setStatus({
                    success: false,
                    msg: 'ACCESS DENIED',
                    details: err.response?.data?.message || 'Invalid Token'
                });
            } finally {
                setLoading(false);
            }
        }, 800);
    };

    return (
        <div style={{
            display: 'flex', flexDirection: 'column',
            alignItems: 'center', justifyContent: 'center', height: '100%',
            background: 'var(--bg-gradient)'
        }}>
            <div className="glass-card anim-slide-up" style={{
                padding: '40px', width: '90%', maxWidth: '400px', textAlign: 'center',
                border: '1px solid white'
            }}>
                <div style={{
                    width: '64px', height: '64px', background: '#e0f2fe', color: 'var(--primary-blue)',
                    borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontSize: '32px', margin: '0 auto 24px auto',
                    boxShadow: '0 4px 12px rgba(14, 165, 233, 0.2)'
                }}>
                    📡
                </div>

                <h1 style={{ fontSize: '24px', marginBottom: '8px', color: 'var(--text-primary)' }}>Gate Scanner</h1>
                <p style={{ color: 'var(--text-secondary)', marginBottom: '32px', lineHeight: '1.5', fontSize: '14px' }}>
                    Enter the token code generated by your EV app to verify reservation at the gate.
                </p>

                <div style={{ marginBottom: '24px', position: 'relative' }}>
                    <input
                        type="text"
                        value={scanResult}
                        onChange={(e) => setScanResult(e.target.value)}
                        placeholder="Paste Token Here..."
                        style={{ textAlign: 'center', fontWeight: 'bold', letterSpacing: '1px' }}
                    />
                </div>

                <button
                    className="btn-primary"
                    onClick={handleScan}
                    style={{ width: '100%', padding: '16px', fontSize: '15px' }}
                    disabled={loading}
                >
                    {loading ? 'VERIFYING...' : 'VERIFY ACCESS'}
                </button>

                {status && (
                    <div className="anim-fade-in" style={{
                        marginTop: '32px', padding: '24px', borderRadius: '16px',
                        background: status.success ? '#ecfdf5' : '#fef2f2',
                        color: status.success ? '#047857' : '#b91c1c',
                        border: `2px solid ${status.success ? '#10b981' : '#ef4444'}`,
                        boxShadow: `0 8px 20px ${status.success ? 'rgba(16, 185, 129, 0.15)' : 'rgba(239, 68, 68, 0.15)'}`
                    }}>
                        <div style={{ fontWeight: '800', marginBottom: '8px', fontSize: '20px', letterSpacing: '0.5px' }}>
                            {status.success ? '✓ ACCESS GRANTED' : '✗ ACCESS DENIED'}
                        </div>
                        <div style={{ fontSize: '13px', opacity: 0.9, fontWeight: '600' }}>
                            {status.details}
                        </div>

                        {status.success && (
                            <div style={{ marginTop: '16px', paddingTop: '16px', borderTop: '1px dashed rgba(0,0,0,0.1)' }}>
                                <div style={{ fontSize: '16px', fontWeight: 'bold', color: 'var(--text-primary)' }}>
                                    {status.chargerName}
                                </div>
                                <div style={{
                                    display: 'inline-block', marginTop: '8px',
                                    padding: '4px 12px', background: '#0ea5e9', color: 'white',
                                    borderRadius: '8px', fontSize: '12px', fontWeight: 'bold'
                                }}>
                                    {status.slotId}
                                </div>
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
};

export default GateScanner;
