from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from datetime import datetime
import os
from services.llm_notes import format_explanation_for_report
from services.specialist import format_specialists_for_report

def generate_pdf_report(prediction_result, explanation, specialists, image_path):
    """
    Generate comprehensive PDF report with diagnosis and recommendations
    """
    # Create reports directory
    os.makedirs("static/reports", exist_ok=True)
    
    # Generate unique filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"medical_report_{timestamp}.pdf"
    filepath = f"static/reports/{filename}"
    
    # Create PDF document
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=30,
        textColor=colors.darkblue
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=12,
        textColor=colors.darkblue
    )
    
    # Title
    story.append(Paragraph("MEDICAL IMAGE ANALYSIS REPORT", title_style))
    story.append(Spacer(1, 20))
    
    # Report metadata
    report_info = f"""
    <b>Report Generated:</b> {datetime.now().strftime("%B %d, %Y at %I:%M %p")}<br/>
    <b>Analysis Method:</b> AI-Powered Image Classification<br/>
    <b>Confidence Level:</b> {prediction_result['confidence']:.1%}<br/>
    """
    story.append(Paragraph(report_info, styles['Normal']))
    story.append(Spacer(1, 20))
    
    # Add analyzed image if exists
    if os.path.exists(image_path):
        try:
            # Resize image to fit in report
            img = Image(image_path, width=3*inch, height=3*inch)
            story.append(Paragraph("ANALYZED IMAGE:", heading_style))
            story.append(img)
            story.append(Spacer(1, 20))
        except Exception as e:
            print(f"Could not add image to report: {e}")
    
    # Diagnosis section
    story.append(Paragraph("DIAGNOSIS RESULTS:", heading_style))
    diagnosis_text = f"""
    <b>Detected Condition:</b> {prediction_result['disease']}<br/>
    <b>Confidence Score:</b> {prediction_result['confidence']:.1%}<br/>
    <b>Classification Probabilities:</b><br/>
    • Disease A: {prediction_result['probabilities']['Disease_A']:.1%}<br/>
    • Disease B: {prediction_result['probabilities']['Disease_B']:.1%}<br/>
    """
    story.append(Paragraph(diagnosis_text, styles['Normal']))
    story.append(Spacer(1, 20))
    
    # Medical explanation
    story.append(Paragraph("MEDICAL INFORMATION:", heading_style))
    explanation_text = format_explanation_for_report(explanation)
    # Convert to HTML-friendly format
    explanation_html = explanation_text.replace('\n', '<br/>')
    story.append(Paragraph(explanation_html, styles['Normal']))
    story.append(Spacer(1, 20))
    
    # Specialists section
    if specialists:
        story.append(Paragraph("SPECIALIST RECOMMENDATIONS:", heading_style))
        specialists_text = format_specialists_for_report(specialists)
        specialists_html = specialists_text.replace('\n', '<br/>')
        story.append(Paragraph(specialists_html, styles['Normal']))
        story.append(Spacer(1, 20))
    
    # Disclaimer
    story.append(Paragraph("IMPORTANT DISCLAIMER:", heading_style))
    disclaimer = """
    <b>This report is generated by an AI system and is intended for informational purposes only. 
    It should not be used as a substitute for professional medical advice, diagnosis, or treatment. 
    Always seek the advice of qualified healthcare providers with any questions regarding medical conditions. 
    Never disregard professional medical advice or delay seeking it because of information from this report.</b>
    """
    story.append(Paragraph(disclaimer, styles['Normal']))
    
    # Build PDF
    doc.build(story)
    
    return filepath

def generate_simple_report(disease, confidence, image_path):
    """Generate a simplified report for quick analysis"""
    os.makedirs("static/reports", exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"quick_report_{timestamp}.pdf"
    filepath = f"static/reports/{filename}"
    
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    story.append(Paragraph("QUICK ANALYSIS REPORT", styles['Title']))
    story.append(Spacer(1, 20))
    
    content = f"""
    <b>Analysis Date:</b> {datetime.now().strftime("%B %d, %Y")}<br/>
    <b>Detected Condition:</b> {disease}<br/>
    <b>Confidence:</b> {confidence:.1%}<br/><br/>
    
    <b>Note:</b> This is a preliminary analysis. Please consult with a healthcare professional for proper diagnosis and treatment.
    """
    
    story.append(Paragraph(content, styles['Normal']))
    doc.build(story)
    
    return filepath